config/routes.rb
Rails.application.routes.draw do
  resources :directors

  scope module: :api do
    resources :media_contents
  end
  
  root "dashboards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
    validates :first_name, presence: true, length: { minimum: 3 }
    validates :last_name, presence: true, length: { minimum: 3, maximum: 10 }
end

app/models/media_content.rb
class MediaContent < ApplicationRecord
    belongs_to :director
    
    validates :name, presence: true
end

app/models/midia_content.rb
class MidiaContent < ApplicationRecord
  belongs_to :director
  
  validates :name, presence: true
end

app/controllers/api/media_contents_controller.rb
module Api
  class MediaContentsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_media_content, only: %i[ show edit update destroy ]

    def index
      @media_contents = MediaContent.all
    end

    def show; end

    def new
      @media_content = MediaContent.new
    end

    def edit; end

    def create
      @media_content = MediaContent.new(media_content_params)

      if @media_content.save
        render 'api/media_contents/show', status: :created
      else
        render json: @media_content.errors, status: :unprocessable_entity
      end
    end

    def update
      if @media_content.update(media_content_params)
        render 'api/media_contents/show', status: :ok
      else
        render json: @media_content.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @media_content.destroy
      render 'api/media_contents/index', status: :ok
    end

    private
      def set_media_content
        @media_content = MediaContent.find(params[:id])
      end

      def media_content_params
        params.require(:media_content).permit(:name, :director_id)
      end
  end
end

app/controllers/api/midia_contents_controller.rb
module Api 
 class MidiaContentsController < ApplicationController
  skip_before_action :verify_authenticity_token  
  before_action :set_midia_content, only: %i[ show edit update destroy ]

   def index
    @midia_contents = MidiaContent.all
   end

   def show; end

   def new
    @midia_content = MidiaContent.new
   end

   def edit; end

   def create
     @midia_content = MidiaContent.new(midia_content_params)

       if @midia_content.save
         render 'api/midia_contents/show', status: :created
       else
          render json: @midia_content.errors, status: :unprocessable_entity 
       end
   end

   def update
     if @midia_content.update(midia_content_params)
       render 'api/midia_contents/show', status: :ok
     else
       render json: @midia_content.errors, status: :unprocessable_entity 
     end
   end

   def destroy
     @midia_content.destroy

      render 'api/midia_content/show', status: :ok
   end

   private
     def set_midia_content
       @midia_content = MidiaContent.find(params[:id])
     end

     def midia_content_params
       params.require(:midia_content).permit(:name, :director_id)
     end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/api/media_contents_controller.rb
module Api

  class MediaContentsController < ApplicationController
    skip_before_action :verify_authencity_token
    before_action :set_media_content, only: %i[ show edit update destroy ]

    def index
      @media_contents = MediaContent.all
    end

    def show; end

    def new
      @media_content = MediaContent.new
    end

    def edit; end

    def create
      @media_content = MediaContent.new(media_content_params)

      if @media_content.save
        render 'api/media_contents/show', status: :created
      else
        render json: @media_content.errors, status: :unprocessable_entity
      end
    end

    def update
      if @media_content.update(media_content_params)
        render 'api/media_contents/show', status: :ok
      else
        render json: @media_content.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @media_content.destroy

      render 'api/media_contents/show', status: ok
    end

    private
      def set_media_content
        @media_content = MediaContent.find(params[:id])
      end

      def media_content_params
        params.require(:media_content).permit(:name, :director_id)
      end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index; end

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: %i[ show edit update destroy ]

  def index
    @directors = Director.all
  end

  def show; end

  def new
    @director = Director.new
  end

  def edit; end

  def create
    @director = Director.new(director_params)

    if @director.save
      redirect_to director_url(@director), notice: t('application.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @director.update(director_params)
      redirect_to director_url(@director), notice: t('application.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @director.destroy
    redirect_to directors_url, notice: t('application.destroyed')
  end

  private
    def set_director
      @director = Director.find(params[:id])
    end

    def director_params
      params.require(:director).permit(:first_name, :last_name)
    end
end

app/controllers/media_contents_controller.rb
class MediaContentsController < ApplicationController
  before_action :set_media_content, only: %i[ show edit update destroy ]

  def index
    @media_contents = MediaContent.all
  end

  def show
  end

  def new
    @media_content = MediaContent.new
  end

  def edit
  end

  def create
    @media_content = MediaContent.new(media_content_params)
      if @media_content.save
        render 'api/media_content/show', status: :create
      else
        render json:@media_content.erorrs, status: :unprocessable_entity
      end
    end
  end

  def update
      if @media_content.update(media_content_params)
        render 'api/media_content/show', status: :ok
      else
        render json:@media_content.erorrs, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @media_content.destroy

      render 'api/media_contents/index', status: ok
    end
  end

  private
    def set_media_content
      @media_content = MediaContent.find(params[:id])
    end

    def media_content_params
      params.require(:media_content).permit(:name, :director_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/direcctors_helper.rb
module DirecctorsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/media_contents_helper.rb
module MediaContentsHelper
end

app/views/dashboards/index.html.haml
.div.m-4
  %h1.mb-4
    = t('application.list_of', model: t('application.cruds_available'))

.float-start.m-4
  = link_to t('application.change_crud'), root_path, class: 'btn btn-danger'

app/views/directors/_director.html.haml
%div{:id => "#{dom_id doctor}"}
  %p
    %strong First_name:
    = director.first_name
  %p
    %strong Last_name:
    = director.last_name

app/views/directors/_form.html.haml
= form_for @director, validate: true do |f|
  -if @director.errors.any?
    .card.mx-4
      .card-body
        %div{style: 'color: red'}
          %h2
            = t('application.can_not_be_saved')
          %ul
            -  @director.errors.each do |error|
              %li= error.full_message

  .form-group.mx-4
  = f.label :first_name, class: "form-label required"
  .div.w-25
    = f.text_field :first_name, autofocus: true, class: "form-control"

  .form-group.mx-4
  = f.label :last_name, class: "form-label required"
  .div.w-25
    = f.text_field :last_name, autofocus: true, class: "form-control"

  .row.mt-4
    .offset-3.col-3
      = link_to t('application.back'), directors_path, class: "btn btn-secondary btn-block"
    .col-3
      = button_tag t('application.save'), class: "btn btn-outline-success btn-block"

app/views/directors/edit.html.haml
%h1= t('application.editing_model', model: t('activerecord.modules.director.one'))

= render "form", director: @director

app/views/directors/index.html.haml
%p{:style => "color: green"}= notice
.div.m-4
  .page.header
    %h1.mb-4
      = t('application.list_of', model: t('activerecord.modules.director.other'))
    .float-end.pb-4
      = link_to t('application.create'), new_director_path, class: "btn btn-primary"

%table.table.table-striped
  %thead
    %tr
      %th= t('activerecord.attributes.director.first_name')
      %th= t('activerecord.attributes.director.last_name')
      %th
      %th
      %th

  %tbody
    - @directors.each do |director|
      %tr
        %td= director.first_name
        %td= director.last_name
        %td= link_to t('application.show'), director, class: "btn btn-info"
        %td= link_to t('application.edit'), edit_director_path(director), class: "btn btn-success"
        %td= button_to t('application.delete'), director, method: :delete, class: "btn btn-danger"

app/views/directors/new.html.haml
%h1= t('application.new_model', model: t('activerecord.modules.director.one'))

= render "form", director: @director

app/views/directors/show.html.haml
%h1= t('activerecord.modules.director.one')

%p#notice= notice

.div.m-4
  .card
    .card-body
      %h5.card-title
        = t('activerecord.attributes.director.first_name')
      %p.card-text= @director.first_name
      %h5.card-title
        = t('activerecord.attributes.director.last_name')
      %p.card-text= @director.last_name

.row.mt-4
  .offset-3.col-3
    = link_to t('application.back'), directors_path, class: "btn btn-secondary"
  .col-3
    = link_to t('application.edit'), edit_director_path(@director), class: "btn btn-success"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BaseProject2023</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= yield %>
</body>
</html>